version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21  # Устанавливается Java 21 Corretto

  pre_build:
    commands:
      - VERSION=$(grep "projectVersion" gradle.properties | awk -F'=' '{print $2}' | tr -d ' ')
        # Извлекается версия проекта из файла gradle.properties

  build:
    commands:
      - echo Build started on `date`
      - echo "Project Version -> $VERSION"
      - gradlew test     # Запуск тестов
      - gradlew build    # Сборка проекта

  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --s3-bucket alexlpn-simpleapp --template-file samTemplate.yml --output-template-file outputSamTemplate.yml
        # Упаковка SAM-шаблона для деплоя
      - ls -la build/libs  # Вывод содержимого папки сборки

artifacts:
  files:
    - build/libs/app-$VERSION.jar
    - outputSamTemplate.yml
    # Эти файлы будут сохранены как артефакты после сборки